services:
  - type: web
    name: fubon-stock-bot
    env: python
    plan: starter

    build:
      pythonVersion: 3.11.6

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: FUBON_USER_ID
        sync: false
      - key: FUBON_PASSWORD
        sync: false
      - key: FUBON_CERT_PATH
        sync: false
      - key: FUBON_CERT_PASSWORD
        sync: false
